### ISSUE TITLE
Considere desbloquear root

### ISSUE THREAD

**Issue by marcussacana** [rodrigo12xd/sockslite#2]
Estou desinstalando o aplicativo por enquanto, Entre usar seu aplicativo e usar root é óbvio que não vou tirar o root.

**Comment by rodrigo12xd** [comment]
Bloqueio de root já foi removido, atualize na PlayStore pra versão 07 e
teste novamente

Em ter., 14 de fev. de 2023 8:07 PM, Marcus André ***@***.***>
escreveu:

**Comment by marcussacana** [comment]
Aplicativo de banco meu precisa do Shamiko (que ele detecta) para funcionar, aplicativo esse, que por sua vez depende do LSPosed, que ele também detecta.

Se eu desligar o LSPosed e o Shamiko temporariamente meu telefone nem liga e fica em bootloop

**Comment by rodrigo12xd** [comment]
Nesse caso não posso ajudar já que é uma proteção contra debug e proteção
de memória do app

Em ter., 14 de fev. de 2023 8:12 PM, Marcus André ***@***.***>
escreveu:

**Comment by marcussacana** [comment]
Eu não esperava que você ajudasse desde que se deu trabalho de colocar isso.
Bem, é isso, vou ir nas antigas e caçar payload manualmente.
